#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Set.Droid.Resource", IsApplication=true)]

namespace Set.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Set.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Set.Droid.Resource.String.Hello;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.error = global::Set.Droid.Resource.Drawable.error;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.info = global::Set.Droid.Resource.Drawable.info;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.success = global::Set.Droid.Resource.Drawable.success;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.warning = global::Set.Droid.Resource.Drawable.warning;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.desc = global::Set.Droid.Resource.Id.desc;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.image = global::Set.Droid.Resource.Id.image;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.title = global::Set.Droid.Resource.Id.title;
			global::Toasts.Forms.Plugin.Droid.Resource.Layout.crouton = global::Set.Droid.Resource.Layout.crouton;
			global::Toasts.Forms.Plugin.Droid.Resource.String.ApplicationName = global::Set.Droid.Resource.String.ApplicationName;
			global::Toasts.Forms.Plugin.Droid.Resource.String.Hello = global::Set.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Set.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Set.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int apptheme_color = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBlue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int comfortable = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int error = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gymnast21 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_accept = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_alarms = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_discard = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_new = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_settings = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_action_time = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_fa_android = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_fa_bullseye = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_fa_calendar = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_fa_caret_down = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_fa_caret_up = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_fa_check = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_fa_check_circle_action = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_fa_check_circle_o = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_fa_chevron_circle_down = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_fa_chevron_circle_right = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_fa_chevron_circle_up = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_fa_chevron_left = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_fa_chevron_right = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_fa_circle = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_fa_circle_o = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_fa_comment_o = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_fa_minus = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_fa_play_circle_action = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_fa_plus = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_fa_star = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_fa_trophy = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int info = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int nosound = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Quotes_1 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int Quotes_10 = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int Quotes_11 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int Quotes_12 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int Quotes_13 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Quotes_14 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int Quotes_15 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int Quotes_16 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int Quotes_17 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Quotes_18 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Quotes_19 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int Quotes_2 = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Quotes_20 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int Quotes_21 = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Quotes_22 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int Quotes_23 = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int Quotes_24 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Quotes_25 = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int Quotes_3 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int Quotes_4 = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int Quotes_5 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int Quotes_6 = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int Quotes_7 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Quotes_8 = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int Quotes_9 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int sound = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int splash = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int SplashScreen = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int success = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int warning = 2130837567;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int desc = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int image = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Bleep = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int OneSet = 2130968577;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060057
			public const int AddProduct = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int AddProductWithGroupSearch = 2131099736;
			
			// aapt resource value: 0x7f060030
			public const int AllowNegQty = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int AllowNegStor = 2131099697;
			
			// aapt resource value: 0x7f06007e
			public const int ApplicationName = 2131099774;
			
			// aapt resource value: 0x7f060054
			public const int ApplyDiscount = 2131099732;
			
			// aapt resource value: 0x7f060028
			public const int AutoMTRL = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int AutoMTRLHint = 2131099689;
			
			// aapt resource value: 0x7f06004e
			public const int CancelInvoiceQuestion = 2131099726;
			
			// aapt resource value: 0x7f06004c
			public const int CancelInvoiceTitle = 2131099724;
			
			// aapt resource value: 0x7f06003d
			public const int CancelationsCount = 2131099709;
			
			// aapt resource value: 0x7f06004f
			public const int CannotCancelBecauseSeriesMissing = 2131099727;
			
			// aapt resource value: 0x7f06004a
			public const int CannotDeleteInvoice = 2131099722;
			
			// aapt resource value: 0x7f06005e
			public const int Code = 2131099742;
			
			// aapt resource value: 0x7f06007c
			public const int ContextMenuOptions = 2131099772;
			
			// aapt resource value: 0x7f06000d
			public const int CustomerDetailsTab1Caption = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int CustomerDetailsTab2Caption = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int CustomerDetailsTitle = 2131099660;
			
			// aapt resource value: 0x7f060010
			public const int CustomerSelectHint = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int CustomerSelectTitle = 2131099663;
			
			// aapt resource value: 0x7f060005
			public const int CustomerTitle = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int CustomersActivityTitle = 2131099652;
			
			// aapt resource value: 0x7f06007b
			public const int Delete = 2131099771;
			
			// aapt resource value: 0x7f06004b
			public const int DeleteInvoiceQuestion = 2131099723;
			
			// aapt resource value: 0x7f060049
			public const int DeleteInvoiceTitle = 2131099721;
			
			// aapt resource value: 0x7f06005d
			public const int Description = 2131099741;
			
			// aapt resource value: 0x7f060066
			public const int Discount = 2131099750;
			
			// aapt resource value: 0x7f060053
			public const int DiscountTotal = 2131099731;
			
			// aapt resource value: 0x7f060012
			public const int FileDoesNotExistMessage = 2131099666;
			
			// aapt resource value: 0x7f06002b
			public const int FiscalYear = 2131099691;
			
			// aapt resource value: 0x7f060024
			public const int FormSeries1 = 2131099684;
			
			// aapt resource value: 0x7f060026
			public const int FormSeries2 = 2131099686;
			
			// aapt resource value: 0x7f06007d
			public const int Hello = 2131099773;
			
			// aapt resource value: 0x7f06002a
			public const int HideGroups = 2131099690;
			
			// aapt resource value: 0x7f06004d
			public const int InvoiceIsCanceled = 2131099725;
			
			// aapt resource value: 0x7f060027
			public const int InvoicePrinter = 2131099687;
			
			// aapt resource value: 0x7f060076
			public const int MtrLinesAlertMessage = 2131099766;
			
			// aapt resource value: 0x7f060072
			public const int MtrLinesAlertTitle = 2131099762;
			
			// aapt resource value: 0x7f060074
			public const int MtrLinesAlertTitleButtonAdd = 2131099764;
			
			// aapt resource value: 0x7f060075
			public const int MtrLinesAlertTitleButtonCancel = 2131099765;
			
			// aapt resource value: 0x7f060073
			public const int MtrLinesAlertTitleButtonUpdate = 2131099763;
			
			// aapt resource value: 0x7f060064
			public const int MtrUnit = 2131099748;
			
			// aapt resource value: 0x7f060077
			public const int MtrlGroupSelectTitle = 2131099767;
			
			// aapt resource value: 0x7f060068
			public const int MtrlLinesEditTab1Caption = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int MtrlLinesEditTab2Caption = 2131099753;
			
			// aapt resource value: 0x7f060063
			public const int MtrlLinesEditTitle = 2131099747;
			
			// aapt resource value: 0x7f060062
			public const int MtrlSelectHint = 2131099746;
			
			// aapt resource value: 0x7f060061
			public const int MtrlSelectTitle = 2131099745;
			
			// aapt resource value: 0x7f06006e
			public const int MtrlStockListTitle = 2131099758;
			
			// aapt resource value: 0x7f060078
			public const int MtrlSubGroupSelectTitle = 2131099768;
			
			// aapt resource value: 0x7f06006b
			public const int NegativeQtyErrorMessage = 2131099755;
			
			// aapt resource value: 0x7f06006a
			public const int NegativeQtyErrorTitle = 2131099754;
			
			// aapt resource value: 0x7f060067
			public const int NetValue = 2131099751;
			
			// aapt resource value: 0x7f06007a
			public const int No = 2131099770;
			
			// aapt resource value: 0x7f06006d
			public const int NotEnoughQtyErrorMessage = 2131099757;
			
			// aapt resource value: 0x7f06006c
			public const int NotEnoughQtyErrorTitle = 2131099756;
			
			// aapt resource value: 0x7f06001d
			public const int OptionsActivityTitle = 2131099677;
			
			// aapt resource value: 0x7f060036
			public const int OptionsTab1Caption = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int OptionsTab2Caption = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int OptionsTab3Caption = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int OptionsTab4Caption = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int OptionsTab5Caption = 2131099706;
			
			// aapt resource value: 0x7f06001e
			public const int OptionsTitle = 2131099678;
			
			// aapt resource value: 0x7f06002f
			public const int OrderOptions = 2131099695;
			
			// aapt resource value: 0x7f06002d
			public const int Payment1 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int Payment2 = 2131099694;
			
			// aapt resource value: 0x7f06002c
			public const int PaymentMethods = 2131099692;
			
			// aapt resource value: 0x7f06005f
			public const int Price = 2131099743;
			
			// aapt resource value: 0x7f060032
			public const int PrintToFile = 2131099698;
			
			// aapt resource value: 0x7f060065
			public const int Quantity = 2131099749;
			
			// aapt resource value: 0x7f060021
			public const int RelatedInvoice = 2131099681;
			
			// aapt resource value: 0x7f060060
			public const int Remain = 2131099744;
			
			// aapt resource value: 0x7f060020
			public const int Routing = 2131099680;
			
			// aapt resource value: 0x7f060043
			public const int SalesActivityTitle = 2131099715;
			
			// aapt resource value: 0x7f06003c
			public const int SalesCount = 2131099708;
			
			// aapt resource value: 0x7f060042
			public const int SalesDayTotal = 2131099714;
			
			// aapt resource value: 0x7f060055
			public const int SalesEditTitle = 2131099733;
			
			// aapt resource value: 0x7f06005b
			public const int SalesSelectFinCode = 2131099739;
			
			// aapt resource value: 0x7f060059
			public const int SalesSelectTitle = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int SalesSelectTrdName = 2131099738;
			
			// aapt resource value: 0x7f06005c
			public const int SalesSelectTrnDate = 2131099740;
			
			// aapt resource value: 0x7f06003b
			public const int SalesStatsTitle = 2131099707;
			
			// aapt resource value: 0x7f060044
			public const int SalesTitle = 2131099716;
			
			// aapt resource value: 0x7f06003e
			public const int SalesTotal = 2131099710;
			
			// aapt resource value: 0x7f060041
			public const int SalesTotalCancelations = 2131099713;
			
			// aapt resource value: 0x7f06003f
			public const int SalesTotalCash = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int SalesTotalCredit = 2131099712;
			
			// aapt resource value: 0x7f060050
			public const int SalesTotalsTitle = 2131099728;
			
			// aapt resource value: 0x7f06006f
			public const int SelectOrder = 2131099759;
			
			// aapt resource value: 0x7f060023
			public const int Series1 = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int Series2 = 2131099685;
			
			// aapt resource value: 0x7f060070
			public const int SortByCode = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int SortByName = 2131099761;
			
			// aapt resource value: 0x7f060015
			public const int ToolsTab1Caption = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int ToolsTab2Caption = 2131099670;
			
			// aapt resource value: 0x7f060018
			public const int ToolsTitle = 2131099672;
			
			// aapt resource value: 0x7f060033
			public const int TrdrDiscountOptions = 2131099699;
			
			// aapt resource value: 0x7f060035
			public const int TrdrEnableAutoDiscount = 2131099701;
			
			// aapt resource value: 0x7f060034
			public const int TrdrEnableDiscount = 2131099700;
			
			// aapt resource value: 0x7f06001f
			public const int WHouse = 2131099679;
			
			// aapt resource value: 0x7f060022
			public const int WHouseHint = 2131099682;
			
			// aapt resource value: 0x7f060079
			public const int Yes = 2131099769;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int btnCancel = 2131099651;
			
			// aapt resource value: 0x7f060047
			public const int btnCancelInv = 2131099719;
			
			// aapt resource value: 0x7f060006
			public const int btnCustomerDetails = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int btnCustomerSelect = 2131099655;
			
			// aapt resource value: 0x7f060046
			public const int btnDelInv = 2131099718;
			
			// aapt resource value: 0x7f060045
			public const int btnEditInv = 2131099717;
			
			// aapt resource value: 0x7f06001a
			public const int btnMtrlStockList = 2131099674;
			
			// aapt resource value: 0x7f060002
			public const int btnOk = 2131099650;
			
			// aapt resource value: 0x7f060051
			public const int btnPayment1 = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int btnPayment2 = 2131099730;
			
			// aapt resource value: 0x7f060048
			public const int btnPrintInv = 2131099720;
			
			// aapt resource value: 0x7f060056
			public const int btnPublish = 2131099734;
			
			// aapt resource value: 0x7f060019
			public const int btnSalesStats = 2131099673;
			
			// aapt resource value: 0x7f060013
			public const int btnTerminate = 2131099667;
			
			// aapt resource value: 0x7f06001b
			public const int btnTestPrinter1 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int btnTestPrinter2 = 2131099676;
			
			// aapt resource value: 0x7f060014
			public const int chkCentralOnly = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int lblCustomerDetails = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int lblCustomerMessage = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int lblCustomerName = 2131099658;
			
			// aapt resource value: 0x7f060017
			public const int lblDatabaseFolder = 2131099671;
			
			// aapt resource value: 0x7f060011
			public const int lblOptionsPathName = 2131099665;
			
			// aapt resource value: 0x7f060009
			public const int lblSelectedCustomer = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int version = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
