#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Set.Droid.Resource", IsApplication=true)]

namespace Set.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Set.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Set.Droid.Resource.String.Hello;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.error = global::Set.Droid.Resource.Drawable.error;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.info = global::Set.Droid.Resource.Drawable.info;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.success = global::Set.Droid.Resource.Drawable.success;
			global::Toasts.Forms.Plugin.Droid.Resource.Drawable.warning = global::Set.Droid.Resource.Drawable.warning;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.desc = global::Set.Droid.Resource.Id.desc;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.image = global::Set.Droid.Resource.Id.image;
			global::Toasts.Forms.Plugin.Droid.Resource.Id.title = global::Set.Droid.Resource.Id.title;
			global::Toasts.Forms.Plugin.Droid.Resource.Layout.crouton = global::Set.Droid.Resource.Layout.crouton;
			global::Toasts.Forms.Plugin.Droid.Resource.String.ApplicationName = global::Set.Droid.Resource.String.ApplicationName;
			global::Toasts.Forms.Plugin.Droid.Resource.String.Hello = global::Set.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int apptheme_color = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonBlue = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int comfortable = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int error = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int gymnast21 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_accept = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_discard = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_new = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_action_settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_action_time = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_fa_android = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_fa_bullseye = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_fa_calendar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_fa_caret_down = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_fa_caret_up = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_fa_check = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_fa_check_circle_action = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_fa_check_circle_o = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_fa_chevron_circle_down = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_fa_chevron_circle_right = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_fa_chevron_circle_up = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_fa_chevron_left = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_fa_chevron_right = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_fa_circle = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_fa_circle_o = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int ic_fa_comment_o = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ic_fa_play_circle_action = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_fa_star = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int icon = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int info = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int nosound = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int sound = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int splash = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int SplashScreen = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int success = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int warning = 2130837538;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080002
			public const int desc = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int image = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int crouton = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int OneSet = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050059
			public const int AddProduct = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int AddProductWithGroupSearch = 2131034202;
			
			// aapt resource value: 0x7f050032
			public const int AllowNegQty = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int AllowNegStor = 2131034163;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050056
			public const int ApplyDiscount = 2131034198;
			
			// aapt resource value: 0x7f05002a
			public const int AutoMTRL = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int AutoMTRLHint = 2131034155;
			
			// aapt resource value: 0x7f050050
			public const int CancelInvoiceQuestion = 2131034192;
			
			// aapt resource value: 0x7f05004e
			public const int CancelInvoiceTitle = 2131034190;
			
			// aapt resource value: 0x7f05003f
			public const int CancelationsCount = 2131034175;
			
			// aapt resource value: 0x7f050051
			public const int CannotCancelBecauseSeriesMissing = 2131034193;
			
			// aapt resource value: 0x7f05004c
			public const int CannotDeleteInvoice = 2131034188;
			
			// aapt resource value: 0x7f050060
			public const int Code = 2131034208;
			
			// aapt resource value: 0x7f05007e
			public const int ContextMenuOptions = 2131034238;
			
			// aapt resource value: 0x7f05000f
			public const int CustomerDetailsTab1Caption = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int CustomerDetailsTab2Caption = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int CustomerDetailsTitle = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int CustomerSelectHint = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int CustomerSelectTitle = 2131034129;
			
			// aapt resource value: 0x7f050007
			public const int CustomerTitle = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int CustomersActivityTitle = 2131034118;
			
			// aapt resource value: 0x7f05007d
			public const int Delete = 2131034237;
			
			// aapt resource value: 0x7f05004d
			public const int DeleteInvoiceQuestion = 2131034189;
			
			// aapt resource value: 0x7f05004b
			public const int DeleteInvoiceTitle = 2131034187;
			
			// aapt resource value: 0x7f05005f
			public const int Description = 2131034207;
			
			// aapt resource value: 0x7f050068
			public const int Discount = 2131034216;
			
			// aapt resource value: 0x7f050055
			public const int DiscountTotal = 2131034197;
			
			// aapt resource value: 0x7f050014
			public const int FileDoesNotExistMessage = 2131034132;
			
			// aapt resource value: 0x7f05002d
			public const int FiscalYear = 2131034157;
			
			// aapt resource value: 0x7f050026
			public const int FormSeries1 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int FormSeries2 = 2131034152;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05002c
			public const int HideGroups = 2131034156;
			
			// aapt resource value: 0x7f05004f
			public const int InvoiceIsCanceled = 2131034191;
			
			// aapt resource value: 0x7f050029
			public const int InvoicePrinter = 2131034153;
			
			// aapt resource value: 0x7f050078
			public const int MtrLinesAlertMessage = 2131034232;
			
			// aapt resource value: 0x7f050074
			public const int MtrLinesAlertTitle = 2131034228;
			
			// aapt resource value: 0x7f050076
			public const int MtrLinesAlertTitleButtonAdd = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int MtrLinesAlertTitleButtonCancel = 2131034231;
			
			// aapt resource value: 0x7f050075
			public const int MtrLinesAlertTitleButtonUpdate = 2131034229;
			
			// aapt resource value: 0x7f050066
			public const int MtrUnit = 2131034214;
			
			// aapt resource value: 0x7f050079
			public const int MtrlGroupSelectTitle = 2131034233;
			
			// aapt resource value: 0x7f05006a
			public const int MtrlLinesEditTab1Caption = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int MtrlLinesEditTab2Caption = 2131034219;
			
			// aapt resource value: 0x7f050065
			public const int MtrlLinesEditTitle = 2131034213;
			
			// aapt resource value: 0x7f050064
			public const int MtrlSelectHint = 2131034212;
			
			// aapt resource value: 0x7f050063
			public const int MtrlSelectTitle = 2131034211;
			
			// aapt resource value: 0x7f050070
			public const int MtrlStockListTitle = 2131034224;
			
			// aapt resource value: 0x7f05007a
			public const int MtrlSubGroupSelectTitle = 2131034234;
			
			// aapt resource value: 0x7f05006d
			public const int NegativeQtyErrorMessage = 2131034221;
			
			// aapt resource value: 0x7f05006c
			public const int NegativeQtyErrorTitle = 2131034220;
			
			// aapt resource value: 0x7f050069
			public const int NetValue = 2131034217;
			
			// aapt resource value: 0x7f05007c
			public const int No = 2131034236;
			
			// aapt resource value: 0x7f05006f
			public const int NotEnoughQtyErrorMessage = 2131034223;
			
			// aapt resource value: 0x7f05006e
			public const int NotEnoughQtyErrorTitle = 2131034222;
			
			// aapt resource value: 0x7f05001f
			public const int OptionsActivityTitle = 2131034143;
			
			// aapt resource value: 0x7f050038
			public const int OptionsTab1Caption = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int OptionsTab2Caption = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int OptionsTab3Caption = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int OptionsTab4Caption = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int OptionsTab5Caption = 2131034172;
			
			// aapt resource value: 0x7f050020
			public const int OptionsTitle = 2131034144;
			
			// aapt resource value: 0x7f050031
			public const int OrderOptions = 2131034161;
			
			// aapt resource value: 0x7f05002f
			public const int Payment1 = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int Payment2 = 2131034160;
			
			// aapt resource value: 0x7f05002e
			public const int PaymentMethods = 2131034158;
			
			// aapt resource value: 0x7f050061
			public const int Price = 2131034209;
			
			// aapt resource value: 0x7f050034
			public const int PrintToFile = 2131034164;
			
			// aapt resource value: 0x7f050067
			public const int Quantity = 2131034215;
			
			// aapt resource value: 0x7f050023
			public const int RelatedInvoice = 2131034147;
			
			// aapt resource value: 0x7f050062
			public const int Remain = 2131034210;
			
			// aapt resource value: 0x7f050022
			public const int Routing = 2131034146;
			
			// aapt resource value: 0x7f050045
			public const int SalesActivityTitle = 2131034181;
			
			// aapt resource value: 0x7f05003e
			public const int SalesCount = 2131034174;
			
			// aapt resource value: 0x7f050044
			public const int SalesDayTotal = 2131034180;
			
			// aapt resource value: 0x7f050057
			public const int SalesEditTitle = 2131034199;
			
			// aapt resource value: 0x7f05005d
			public const int SalesSelectFinCode = 2131034205;
			
			// aapt resource value: 0x7f05005b
			public const int SalesSelectTitle = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int SalesSelectTrdName = 2131034204;
			
			// aapt resource value: 0x7f05005e
			public const int SalesSelectTrnDate = 2131034206;
			
			// aapt resource value: 0x7f05003d
			public const int SalesStatsTitle = 2131034173;
			
			// aapt resource value: 0x7f050046
			public const int SalesTitle = 2131034182;
			
			// aapt resource value: 0x7f050040
			public const int SalesTotal = 2131034176;
			
			// aapt resource value: 0x7f050043
			public const int SalesTotalCancelations = 2131034179;
			
			// aapt resource value: 0x7f050041
			public const int SalesTotalCash = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int SalesTotalCredit = 2131034178;
			
			// aapt resource value: 0x7f050052
			public const int SalesTotalsTitle = 2131034194;
			
			// aapt resource value: 0x7f050071
			public const int SelectOrder = 2131034225;
			
			// aapt resource value: 0x7f050025
			public const int Series1 = 2131034149;
			
			// aapt resource value: 0x7f050027
			public const int Series2 = 2131034151;
			
			// aapt resource value: 0x7f050072
			public const int SortByCode = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int SortByName = 2131034227;
			
			// aapt resource value: 0x7f050017
			public const int ToolsTab1Caption = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int ToolsTab2Caption = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int ToolsTitle = 2131034138;
			
			// aapt resource value: 0x7f050035
			public const int TrdrDiscountOptions = 2131034165;
			
			// aapt resource value: 0x7f050037
			public const int TrdrEnableAutoDiscount = 2131034167;
			
			// aapt resource value: 0x7f050036
			public const int TrdrEnableDiscount = 2131034166;
			
			// aapt resource value: 0x7f050021
			public const int WHouse = 2131034145;
			
			// aapt resource value: 0x7f050024
			public const int WHouseHint = 2131034148;
			
			// aapt resource value: 0x7f05007b
			public const int Yes = 2131034235;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int btnCancel = 2131034117;
			
			// aapt resource value: 0x7f050049
			public const int btnCancelInv = 2131034185;
			
			// aapt resource value: 0x7f050008
			public const int btnCustomerDetails = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int btnCustomerSelect = 2131034121;
			
			// aapt resource value: 0x7f050048
			public const int btnDelInv = 2131034184;
			
			// aapt resource value: 0x7f050047
			public const int btnEditInv = 2131034183;
			
			// aapt resource value: 0x7f05001c
			public const int btnMtrlStockList = 2131034140;
			
			// aapt resource value: 0x7f050004
			public const int btnOk = 2131034116;
			
			// aapt resource value: 0x7f050053
			public const int btnPayment1 = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int btnPayment2 = 2131034196;
			
			// aapt resource value: 0x7f05004a
			public const int btnPrintInv = 2131034186;
			
			// aapt resource value: 0x7f050058
			public const int btnPublish = 2131034200;
			
			// aapt resource value: 0x7f05001b
			public const int btnSalesStats = 2131034139;
			
			// aapt resource value: 0x7f050015
			public const int btnTerminate = 2131034133;
			
			// aapt resource value: 0x7f05001d
			public const int btnTestPrinter1 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int btnTestPrinter2 = 2131034142;
			
			// aapt resource value: 0x7f050016
			public const int chkCentralOnly = 2131034134;
			
			// aapt resource value: 0x7f05000d
			public const int lblCustomerDetails = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int lblCustomerMessage = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int lblCustomerName = 2131034124;
			
			// aapt resource value: 0x7f050019
			public const int lblDatabaseFolder = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int lblOptionsPathName = 2131034131;
			
			// aapt resource value: 0x7f05000b
			public const int lblSelectedCustomer = 2131034123;
			
			// aapt resource value: 0x7f050003
			public const int version = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
