//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Set.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Set.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exercise.
        /// </summary>
        internal static string AddExerciseTitle {
            get {
                return ResourceManager.GetString("AddExerciseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string AnalysisTitle {
            get {
                return ResourceManager.GetString("AnalysisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        internal static string AuthorTitle {
            get {
                return ResourceManager.GetString("AuthorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        internal static string ChartsTitle {
            get {
                return ResourceManager.GetString("ChartsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight per workout.
        /// </summary>
        internal static string ChartsType1Title {
            get {
                return ResourceManager.GetString("ChartsType1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps per workout.
        /// </summary>
        internal static string ChartsType2Title {
            get {
                return ResourceManager.GetString("ChartsType2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout data have been cleared.
        /// </summary>
        internal static string ClearWorkoutDataCompleted {
            get {
                return ResourceManager.GetString("ClearWorkoutDataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all workout data?.
        /// </summary>
        internal static string ClearWorkoutDataQuestion {
            get {
                return ResourceManager.GetString("ClearWorkoutDataQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string CommentTitle {
            get {
                return ResourceManager.GetString("CommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment Workout.
        /// </summary>
        internal static string CommentWorkoutTitle {
            get {
                return ResourceManager.GetString("CommentWorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits (with many thanks!).
        /// </summary>
        internal static string CreditTitle {
            get {
                return ResourceManager.GetString("CreditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string CurrentWorkoutTitle {
            get {
                return ResourceManager.GetString("CurrentWorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exercise.
        /// </summary>
        internal static string EditExerciseTitle {
            get {
                return ResourceManager.GetString("EditExerciseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this exercise? Any workout data for this exercise will be deleted as well..
        /// </summary>
        internal static string ExerciseDeleteQuestion {
            get {
                return ResourceManager.GetString("ExerciseDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Exercise.
        /// </summary>
        internal static string ExerciseDeleteQuestionTitle {
            get {
                return ResourceManager.GetString("ExerciseDeleteQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise or weight machine name.
        /// </summary>
        internal static string ExerciseLabel {
            get {
                return ResourceManager.GetString("ExerciseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type an exercise name.
        /// </summary>
        internal static string ExerciseNameIsRequired {
            get {
                return ResourceManager.GetString("ExerciseNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ExercisePageDetails {
            get {
                return ResourceManager.GetString("ExercisePageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Rules.
        /// </summary>
        internal static string ExercisePageTrainingRules {
            get {
                return ResourceManager.GetString("ExercisePageTrainingRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise saved.
        /// </summary>
        internal static string ExerciseSaved {
            get {
                return ResourceManager.GetString("ExerciseSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string ExercisesTitle {
            get {
                return ResourceManager.GetString("ExercisesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample data have been loaded.
        /// </summary>
        internal static string LoadSampleDataCompleted {
            get {
                return ResourceManager.GetString("LoadSampleDataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the + button to create an Exercise.
        /// </summary>
        internal static string NoExerciseDataLine1 {
            get {
                return ResourceManager.GetString("NoExerciseDataLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoExerciseDataLine2 {
            get {
                return ResourceManager.GetString("NoExerciseDataLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Exercises here yet!.
        /// </summary>
        internal static string NoExerciseDataTitle {
            get {
                return ResourceManager.GetString("NoExerciseDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add exercises and set your training program in the Exercises menu..
        /// </summary>
        internal static string NoWorkoutDataLine1 {
            get {
                return ResourceManager.GetString("NoWorkoutDataLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You also need to rest. If this is your rest day, enjoy it!.
        /// </summary>
        internal static string NoWorkoutDataLine2 {
            get {
                return ResourceManager.GetString("NoWorkoutDataLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No training today!.
        /// </summary>
        internal static string NoWorkoutDataTitle {
            get {
                return ResourceManager.GetString("NoWorkoutDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight increment or plate weight ({0}).
        /// </summary>
        internal static string PlateWeightLabel {
            get {
                return ResourceManager.GetString("PlateWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Reps / Weight.
        /// </summary>
        internal static string PreviousTitle {
            get {
                return ResourceManager.GetString("PreviousTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        internal static string Reps {
            get {
                return ResourceManager.GetString("Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} in every {0} workouts.
        /// </summary>
        internal static string RepsIncrementDescription {
            get {
                return ResourceManager.GetString("RepsIncrementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No increment.
        /// </summary>
        internal static string RepsIncrementDisabledDescr {
            get {
                return ResourceManager.GetString("RepsIncrementDisabledDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} every other time.
        /// </summary>
        internal static string RepsIncrementEveryOtherTimeDescription {
            get {
                return ResourceManager.GetString("RepsIncrementEveryOtherTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} in every workout.
        /// </summary>
        internal static string RepsIncrementZeroWorkCountDescr {
            get {
                return ResourceManager.GetString("RepsIncrementZeroWorkCountDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no backups available.
        /// </summary>
        internal static string RestoreNoBackupMessage {
            get {
                return ResourceManager.GetString("RestoreNoBackupMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestoreNoBackupTitle {
            get {
                return ResourceManager.GetString("RestoreNoBackupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to restore the {0} backup? .
        /// </summary>
        internal static string RestoreQuestionMessage {
            get {
                return ResourceManager.GetString("RestoreQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string RestoreQuestionTitle {
            get {
                return ResourceManager.GetString("RestoreQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Start.
        /// </summary>
        internal static string RestTimerAutoStartTitle {
            get {
                return ResourceManager.GetString("RestTimerAutoStartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string RestTimerPause {
            get {
                return ResourceManager.GetString("RestTimerPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound.
        /// </summary>
        internal static string RestTimerPlaySoundsTitle {
            get {
                return ResourceManager.GetString("RestTimerPlaySoundsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RestTimerReset {
            get {
                return ResourceManager.GetString("RestTimerReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string RestTimerStart {
            get {
                return ResourceManager.GetString("RestTimerStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest Timer.
        /// </summary>
        internal static string RestTimerTitle {
            get {
                return ResourceManager.GetString("RestTimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version info and credits.
        /// </summary>
        internal static string SettingsAboutHint {
            get {
                return ResourceManager.GetString("SettingsAboutHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsAboutTitle {
            get {
                return ResourceManager.GetString("SettingsAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup your data locally to SD Card.
        /// </summary>
        internal static string SettingsBackupLocallyHint {
            get {
                return ResourceManager.GetString("SettingsBackupLocallyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string SettingsBackupLocallyTitle {
            get {
                return ResourceManager.GetString("SettingsBackupLocallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup created at {0}.
        /// </summary>
        internal static string SettingsBackupToastMessageOnSuccess {
            get {
                return ResourceManager.GetString("SettingsBackupToastMessageOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        internal static string SettingsBackupToastTitleOnSuccess {
            get {
                return ResourceManager.GetString("SettingsBackupToastTitleOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all Workout Data but keeps settings and your exercises data.
        /// </summary>
        internal static string SettingsClearWorkoutDataHint {
            get {
                return ResourceManager.GetString("SettingsClearWorkoutDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Workout Data.
        /// </summary>
        internal static string SettingsClearWorkoutDataTitle {
            get {
                return ResourceManager.GetString("SettingsClearWorkoutDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA.
        /// </summary>
        internal static string SettingsDataTitle {
            get {
                return ResourceManager.GetString("SettingsDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps to do more in every workout.
        /// </summary>
        internal static string SettingsExerciseGoalHint {
            get {
                return ResourceManager.GetString("SettingsExerciseGoalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Goal.
        /// </summary>
        internal static string SettingsExerciseGoalTitle {
            get {
                return ResourceManager.GetString("SettingsExerciseGoalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exported to {0}.
        /// </summary>
        internal static string SettingsExportWorkoutDataCompleted {
            get {
                return ResourceManager.GetString("SettingsExportWorkoutDataCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export your workout data to a popular file format.
        /// </summary>
        internal static string SettingsExportWorkoutDataHint {
            get {
                return ResourceManager.GetString("SettingsExportWorkoutDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as .CSV (view in a spreasheet application).
        /// </summary>
        internal static string SettingsExportWorkoutDataOption1 {
            get {
                return ResourceManager.GetString("SettingsExportWorkoutDataOption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Workout Data.
        /// </summary>
        internal static string SettingsExportWorkoutDataTitle {
            get {
                return ResourceManager.GetString("SettingsExportWorkoutDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL.
        /// </summary>
        internal static string SettingsGeneralTitle {
            get {
                return ResourceManager.GetString("SettingsGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup on {0}.
        /// </summary>
        internal static string SettingsLastBackupDate {
            get {
                return ResourceManager.GetString("SettingsLastBackupDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load sample data to get you started.
        /// </summary>
        internal static string SettingsLoadSampleDataHint {
            get {
                return ResourceManager.GetString("SettingsLoadSampleDataHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Sample Data.
        /// </summary>
        internal static string SettingsLoadSampleDataTitle {
            get {
                return ResourceManager.GetString("SettingsLoadSampleDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of reps to advance to the next weight level.
        /// </summary>
        internal static string SettingsMaxRepsHint {
            get {
                return ResourceManager.GetString("SettingsMaxRepsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Reps.
        /// </summary>
        internal static string SettingsMaxRepsTitle {
            get {
                return ResourceManager.GetString("SettingsMaxRepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you can&apos;t do at least this number of Reps you should go back a weight level.
        /// </summary>
        internal static string SettingsMinRepsHint {
            get {
                return ResourceManager.GetString("SettingsMinRepsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Reps.
        /// </summary>
        internal static string SettingsMinRepsTitle {
            get {
                return ResourceManager.GetString("SettingsMinRepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a motivational image pack.
        /// </summary>
        internal static string SettingsMotivationalImagePacksHint {
            get {
                return ResourceManager.GetString("SettingsMotivationalImagePacksHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Pack.
        /// </summary>
        internal static string SettingsMotivationalImagePacksTitle {
            get {
                return ResourceManager.GetString("SettingsMotivationalImagePacksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOTIVATION.
        /// </summary>
        internal static string SettingsMotivationTitle {
            get {
                return ResourceManager.GetString("SettingsMotivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTHER.
        /// </summary>
        internal static string SettingsOtherTitle {
            get {
                return ResourceManager.GetString("SettingsOtherTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculation finished!.
        /// </summary>
        internal static string SettingsRecalcStatisticsFinished {
            get {
                return ResourceManager.GetString("SettingsRecalcStatisticsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate Statistics.
        /// </summary>
        internal static string SettingsRecalcStatisticsTitle {
            get {
                return ResourceManager.GetString("SettingsRecalcStatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate all statistics and trophies.
        /// </summary>
        internal static string SettingsRecalcStatisticsTitleHint {
            get {
                return ResourceManager.GetString("SettingsRecalcStatisticsTitleHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore your data from a previously created backup.
        /// </summary>
        internal static string SettingsRestoreLocallyHint {
            get {
                return ResourceManager.GetString("SettingsRestoreLocallyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string SettingsRestoreLocallyTitle {
            get {
                return ResourceManager.GetString("SettingsRestoreLocallyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data restored successfully.
        /// </summary>
        internal static string SettingsRestoreToastMessageOnSuccess {
            get {
                return ResourceManager.GetString("SettingsRestoreToastMessageOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string SettingsRestoreToastTitleOnSuccess {
            get {
                return ResourceManager.GetString("SettingsRestoreToastTitleOnSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show motivational images in rest timer page.
        /// </summary>
        internal static string SettingsShowImagesInRestTimerTitle {
            get {
                return ResourceManager.GetString("SettingsShowImagesInRestTimerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show motivational images in workout tracking page.
        /// </summary>
        internal static string SettingsShowImagesPackInWorkoutTitle {
            get {
                return ResourceManager.GetString("SettingsShowImagesPackInWorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can override these rules in each exercise.
        /// </summary>
        internal static string SettingsTrainingRulesHint {
            get {
                return ResourceManager.GetString("SettingsTrainingRulesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRAINING RULES.
        /// </summary>
        internal static string SettingsTrainingRulesTitle {
            get {
                return ResourceManager.GetString("SettingsTrainingRulesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit System.
        /// </summary>
        internal static string SettingsUnitSystemTitle {
            get {
                return ResourceManager.GetString("SettingsUnitSystemTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the previous Reps and Weight in the exercise workout page.
        /// </summary>
        internal static string ShowPreviousRepsWeight {
            get {
                return ResourceManager.GetString("ShowPreviousRepsWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the target Reps and Weight in the exercise workout page.
        /// </summary>
        internal static string ShowTargetRepsWeight {
            get {
                return ResourceManager.GetString("ShowTargetRepsWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support and feedback to.
        /// </summary>
        internal static string SupportTitle {
            get {
                return ResourceManager.GetString("SupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Reps / Weight.
        /// </summary>
        internal static string TargetTitle {
            get {
                return ResourceManager.GetString("TargetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ToastErrorTitle {
            get {
                return ResourceManager.GetString("ToastErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOMORROW.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training on.
        /// </summary>
        internal static string TrainingDaysLabel {
            get {
                return ResourceManager.GetString("TrainingDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Program.
        /// </summary>
        internal static string TrainingProgram {
            get {
                return ResourceManager.GetString("TrainingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imperial (Lbs).
        /// </summary>
        internal static string UnitSystemImperial {
            get {
                return ResourceManager.GetString("UnitSystemImperial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metric (Kgs).
        /// </summary>
        internal static string UnitSystemMetric {
            get {
                return ResourceManager.GetString("UnitSystemMetric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reps value.
        /// </summary>
        internal static string WorkoutInvalidReps {
            get {
                return ResourceManager.GetString("WorkoutInvalidReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Weight value.
        /// </summary>
        internal static string WorkoutInvalidWeight {
            get {
                return ResourceManager.GetString("WorkoutInvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter how many Reps you did.
        /// </summary>
        internal static string WorkoutRepsIsRequired {
            get {
                return ResourceManager.GetString("WorkoutRepsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        internal static string Workouts {
            get {
                return ResourceManager.GetString("Workouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout saved.
        /// </summary>
        internal static string WorkoutSaved {
            get {
                return ResourceManager.GetString("WorkoutSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string WorkoutTitle {
            get {
                return ResourceManager.GetString("WorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Weight of this workout.
        /// </summary>
        internal static string WorkoutWeightIsRequired {
            get {
                return ResourceManager.GetString("WorkoutWeightIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YESTERDAY.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
