//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Set.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Set.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exercise.
        /// </summary>
        internal static string AddExerciseTitle {
            get {
                return ResourceManager.GetString("AddExerciseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string CurrentWorkoutTitle {
            get {
                return ResourceManager.GetString("CurrentWorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Exercise.
        /// </summary>
        internal static string EditExerciseTitle {
            get {
                return ResourceManager.GetString("EditExerciseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise or weight machine name.
        /// </summary>
        internal static string ExerciseLabel {
            get {
                return ResourceManager.GetString("ExerciseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type an exercise name.
        /// </summary>
        internal static string ExerciseNameIsRequired {
            get {
                return ResourceManager.GetString("ExerciseNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise saved.
        /// </summary>
        internal static string ExerciseSaved {
            get {
                return ResourceManager.GetString("ExerciseSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercises.
        /// </summary>
        internal static string ExercisesTitle {
            get {
                return ResourceManager.GetString("ExercisesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string MinuteRestTimerDescription {
            get {
                return ResourceManager.GetString("MinuteRestTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string MinutesRestTimerDescription {
            get {
                return ResourceManager.GetString("MinutesRestTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string NotesLabel {
            get {
                return ResourceManager.GetString("NotesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight increment or plate weight ({0}).
        /// </summary>
        internal static string PlateWeightLabel {
            get {
                return ResourceManager.GetString("PlateWeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Reps.
        /// </summary>
        internal static string PreviousRepsTitle {
            get {
                return ResourceManager.GetString("PreviousRepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Weight.
        /// </summary>
        internal static string PreviousWeightTitle {
            get {
                return ResourceManager.GetString("PreviousWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reps.
        /// </summary>
        internal static string Reps {
            get {
                return ResourceManager.GetString("Reps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} in every {0} workouts.
        /// </summary>
        internal static string RepsIncrementDescription {
            get {
                return ResourceManager.GetString("RepsIncrementDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No increment.
        /// </summary>
        internal static string RepsIncrementDisabledDescr {
            get {
                return ResourceManager.GetString("RepsIncrementDisabledDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} every other time.
        /// </summary>
        internal static string RepsIncrementEveryOtherTimeDescription {
            get {
                return ResourceManager.GetString("RepsIncrementEveryOtherTimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} in every workout.
        /// </summary>
        internal static string RepsIncrementZeroWorkCountDescr {
            get {
                return ResourceManager.GetString("RepsIncrementZeroWorkCountDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to secs.
        /// </summary>
        internal static string SecondsRestTimerDescription {
            get {
                return ResourceManager.GetString("SecondsRestTimerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Reps.
        /// </summary>
        internal static string TargetRepsTitle {
            get {
                return ResourceManager.GetString("TargetRepsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Weight.
        /// </summary>
        internal static string TargetWeightTitle {
            get {
                return ResourceManager.GetString("TargetWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        internal static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Program.
        /// </summary>
        internal static string TrainingProgram {
            get {
                return ResourceManager.GetString("TrainingProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Reps value.
        /// </summary>
        internal static string WorkoutInvalidReps {
            get {
                return ResourceManager.GetString("WorkoutInvalidReps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Weight value.
        /// </summary>
        internal static string WorkoutInvalidWeight {
            get {
                return ResourceManager.GetString("WorkoutInvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter how many Reps you did.
        /// </summary>
        internal static string WorkoutRepsIsRequired {
            get {
                return ResourceManager.GetString("WorkoutRepsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workouts.
        /// </summary>
        internal static string Workouts {
            get {
                return ResourceManager.GetString("Workouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout saved.
        /// </summary>
        internal static string WorkoutSaved {
            get {
                return ResourceManager.GetString("WorkoutSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        internal static string WorkoutTitle {
            get {
                return ResourceManager.GetString("WorkoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Weight of this workout.
        /// </summary>
        internal static string WorkoutWeightIsRequired {
            get {
                return ResourceManager.GetString("WorkoutWeightIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide rest timer.
        /// </summary>
        internal static string ZeroSecsRestTimerDescription {
            get {
                return ResourceManager.GetString("ZeroSecsRestTimerDescription", resourceCulture);
            }
        }
    }
}
